Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/03/2020
Var
// Seção de Declarações das variáveis 
n, s1 : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Me de um número: ")
leia(n)
s1 <- n-1
escreval("Seu antecessor é: ",s1)


Fimalgoritmo