Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/03/2020
Var
// Seção de Declarações das variáveis 
x : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
x<- 10
escreval(x)
enquanto x>1 faca
x<- x-1
escreval(x)
fimenquanto

Fimalgoritmo